# Generated by Django 2.0.1 on 2018-08-26 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('skills', models.ManyToManyField(to='skills.Skill')),
            ],
        ),
    ]
