# Generated by Django 2.0.1 on 2018-08-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
