# Generated by Django 2.0.1 on 2018-10-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'bio',
            },
        ),
        migrations.CreateModel(
            name='SelfPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='me/')),
            ],
            options={
                'verbose_name_plural': 'Self Photo',
            },
        ),
    ]
